apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: keda-operator-metrics-apiserver
  namespaceSelector:
    matchNames:
      - keda
  endpoints:
    - port: metrics
      interval: 15s
