USER-SUPPLIED VALUES:
alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: gp3
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - equal:
      - alertname
      source_match:
        severity: critical
      target_match:
        severity: warning
    receivers:
    - name: slack
      slack_configs:
      - api_url: SLACK_WEBHOOK_PLACEHOLDER
        channel: '#alerts'
        send_resolved: true
        text: '{{ range .Alerts }} *severity*: {{ .Labels.severity }} *summary*: {{
          .Annotations.summary }} *starts*: {{ .StartsAt.Format "2006-01-02 15:04:05"
          }} --- {{ end }}'
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
    route:
      group_by:
      - alertname
      - severity
      group_interval: 5m
      group_wait: 10s
      receiver: slack
      repeat_interval: 1h
      routes:
      - match:
          severity: critical
        receiver: slack
        repeat_interval: 15m
grafana:
  additionalDataSources:
  - access: proxy
    editable: false
    name: Loki
    type: loki
    uid: loki
    url: http://loki.monitoring.svc.cluster.local:3100
  adminPassword: soldesk1.
  adminUser: root
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - disableDeletion: false
        editable: true
        folder: ""
        name: default
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
  grafana.ini:
    server:
      root_url: '%(protocol)s://%(domain)s/grafana'
      serve_from_sub_path: true
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: gp3
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: read-api
      kubernetes_sd_configs:
      - namespaces:
          names:
          - ticketing
        role: endpoints
      relabel_configs:
      - action: keep
        regex: read-api
        source_labels:
        - __meta_kubernetes_service_name
      - action: keep
        regex: metrics
        source_labels:
        - __meta_kubernetes_endpoint_port_name
    - job_name: write-api
      kubernetes_sd_configs:
      - namespaces:
          names:
          - ticketing
        role: endpoints
      relabel_configs:
      - action: keep
        regex: write-api
        source_labels:
        - __meta_kubernetes_service_name
      - action: keep
        regex: metrics
        source_labels:
        - __meta_kubernetes_endpoint_port_name
    - job_name: worker-svc
      kubernetes_sd_configs:
      - namespaces:
          names:
          - ticketing
        role: endpoints
      relabel_configs:
      - action: keep
        regex: worker-svc
        source_labels:
        - __meta_kubernetes_service_name
      - action: keep
        regex: metrics
        source_labels:
        - __meta_kubernetes_endpoint_port_name
    - job_name: redis-exporter
      static_configs:
      - targets:
        - redis-exporter.ticketing.svc.cluster.local:9121
    resources:
      limits:
        cpu: 500m
        memory: 768Mi
      requests:
        cpu: 200m
        memory: 400Mi
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: gp3
prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
